### ISSUE TITLE
Rechazado

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/exercise-insta#1]
- [x] Pasa los styles de index.html a styles.css
- [x] Usa font-awesome con nombres de clases
- [x] Cuadra los contenidos de header (h1, h2 con el icono)
- [x] El tamaño del post tiene que ser más pequeño (como un post de Instagram)
- [x] Propiedad "align" de CSS no existe

**Comment by ghost** [comment]
Listo, ya arregle los 5 issues y volví a entregar el proyecto. Gracias!

**Comment by t0kyolover** [comment]
@ANicolasOrtiz Hiciste el push? No están los cambios.
